### ISSUE TITLE
Documentation for modular implementation

### ISSUE THREAD

**Issue by shwethanidd** [eclipse-volttron/volttron-docs#1]

**Comment by schandrika** [comment]
@shwethanidd we have a version of modular docs at **https://eclipse-volttron.readthedocs.io/en/latest/** Please review and close this issue or let me know what else can be added/improved

**Comment by shwethanidd** [comment]
@schandrika: I just noticed this today. Introduction section does not have any mention of Eclipse foundation and VOLTTRON being part of it.
